# Generated by Django 6.1.1 on 2026-09-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=400)),
                ('ecgains', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=10)),
                ('contact_email', models.EmailField(max_length=254)),
                ('developer', models.CharField(choices=[('kabil', 'Kabil Raya'), ('john', 'John Doe'), ('sam', 'Sam Jackson')], max_length=100)),
                ('module_name', models.CharField(max_length=100)),
                ('bid_type', models.CharField(choices=[('new', 'New'), ('update', 'Update')], max_length=50)),
                ('procurement_type', models.CharField(choices=[('spider', 'Spider'), ('amr', 'AMR'), ('manual', 'Manual')], max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('main_bid_link', models.URLField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('high', 'High'), ('normal', 'Normal')], max_length=20)),
                ('has_bids', models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default=False, max_length=10)),
            ],
        ),
    ]
